### ISSUE TITLE
[example] add another example, like a tutorial,  jupyter notebook would be an option for this

### ISSUE THREAD

**Issue by govarguz** [lanl/GLUE#9]
Hi again, I saw the example and I got an idea on how it works, however, there are plenty functions e.g. in alInterface.py and the rest of the GLUcode which are not pretty clear to me (this is also related to the documentation part). 
Adding a step-by-step example on how to use it in LAMMPS would improve also the documentation. Here I would suggest to use a jupyter notebook, or similar to better visualize the workflow.

Part of https://github.com/openjournals/joss-reviews/issues/4822

**Comment by rspavel** [comment]
We looked into Jupyter (as well as a potential installation of the service as a "normal" python package) but it did not seem to be a good fit due to the use of the python based `GLUECode_Service` as, well, a service. But I did improve the example scripts and add one to use the training data generation script.
